### ISSUE TITLE
Sat May 18th Project Goals

### ISSUE THREAD

**Issue by ecshaff** [ekahialoha/SplitIt#11]
App.js Shifts:
(Emmy 12-3:30pm, Christian 3:30-7pm, Matt 7-10:30pm)

Emmy:
Display House Name and Owner
Fix Delete and Edit Routes
Create Add Member Button with Full Functionality

**Comment by MattyTamale** [comment]
Matt:
App.js Time Slot: 7-10:30pm
Code the Edit and Delete Routes: **Delete Route finished/need to tweak edit route to display updated info.**
Add HTML for Edit and Delete Routes: **Also finished but edit route needs additional show and hide feature?**
Adjust layout of displayed elements: **Need to link show/hide functionality to edit form**

**Comment by ekahialoha** [comment]
Christian:
~Separate out auth and user landing page~
~Users landing page (after auth completed)~ **page showing need to figure out what content to display**
~Manage Account, update email, password, name, etc~ **new password optional, current password required**
~Auth check on page refresh~
