### ISSUE TITLE
Sun May 19th Project Goals

### ISSUE THREAD

**Issue by ecshaff** [ekahialoha/SplitIt#12]
App.js Shifts:
(12-3:30pm, 3:30-7pm, 7-10:30pm)

Team Goals: 
Create 1-2 Sample App Designs in https://www.canva.com/

Emmy:
Display Members on House Page
Add Edit and Delete Members Button 
Start Splitting Up The House HTML

**Comment by MattyTamale** [comment]
Matt:
-Display multiple bills: current bug only permits one = **FIXED**
-Add functionality to edit button to hide/show edit form. = **DONE**
-Link to house and users models.
-UX design ideas = **DONE**

**Comment by ekahialoha** [comment]
Christian:
Registration/Update Account Field Validation
Design wireframe
