### ISSUE TITLE
API/FrontEnd: Bills

### ISSUE THREAD

**Issue by ekahialoha** [ekahialoha/SplitIt#6]
Route:
Create, post
Edit, put
Delete, delete

Connect bill model

Frontend View:
create form
Show bill, show details from model w/list of users showing paid or not
Edit view

**Comment by MattyTamale** [comment]
Create, Edit, Delete Routes created. 

Bill Model has been started.

Create form for Bills has been made but needs proper inputs once model is finished.

createBill() added to app.js file but needs additional information once model is finished.
